### PR TITLE
Fix issues #2 and #3 (making elm-yesod compile against yesod 1.1.7.1)

### PR DESCRIPTION
**Pull request by ngunn**
Fix elm-yesod to compile against yesod 1.1.7.1 (shakespeare 1.1.1).
Broken by "Disable legacy ToJavascript instances" change to julius 1.0.2 -> 1.1.0
See:
https://github.com/yesodweb/shakespeare/commit/d5a1b570198d79becee71f5a06fe3e45fba8a902#shakespeare-js/Text/Julius.hs

Fixes issues #2 and #3

### CODE REVIEW

**Comment by tazjin** [comment]
Thanks for this - I've been way too busy lately :/

Will also push to Hackage after testing tomorrow evening.

**Comment by DonaldScott** [comment]
Thanks!

Was this fix to #2 and #3 also related to the following Issue raised earlier today on the Elm GitHub page?

On Ubuntu 12.04 (32-bit) on AWS EC2 (after fresh install of haskell-platform and yesod-platform): "cabal install elm-yesod" gives error at Language/Elm/Yesod.hs:(65,1)-(73,46)
https://github.com/evancz/Elm/issues/109

I presume it was (since that Issue on Elm's GitHub page, raised by me, involved ToJavaScript and Yesod-1.1.7.1, just like #3 did).

It's late here now but I will test out this fix over the weekend on my installation of Yesod. 

It seems like that Issue was the only thing standing in the way of getting elm-yesod running in my particular installation.

Thanks and it's good to see current activity on the elm-yesod page!

**Comment by DonaldScott** [comment]
PS - Sorry to ask some very basic questions, but I'm just getting started using GitHub, Cabal, Hackage etc.

Here goes:

I see that the fix above involved making the following tiny change in the file Elm/Language/Yesod.hs in the package elm-yesod:

https://github.com/ngunn/elm-yesod/commit/1a02abcb327dbe8cbdcef1ce6d1585bccbf741ac#Language/Elm/Yesod.hs

I also see above that this change has not yet been "pushed" to Hackage, although it will be soon.

So, since cabal "pulls" packages from Hackage, it seems that if I were to simply repeat the command now:

```
cabal install elm-yesod
```

this would not pull in the file incorporating this change.

As an alternative, I tried searching (on my Ubuntu) using:

```
sudo find / -name Yesod.hs
```

to find a file Yesod.hs, but I don't see one anywhere, so I guess cabal doesn't save local copies of source files, so it would not even make sense to attempt to update a local copy of Elm/Language/Yesod.hs - since there is none.

The closest thing I found poking around on Ubuntu was as follows:

```
ubuntu:/$ ls -l  /home/ubuntu/.cabal/lib/Elm-0.7.1.1/ghc-7.4.1/Language/Elm
total 12
-rw-r--r-- 1 ubuntu ubuntu 9780 Mar  1 16:04 Quasi.hi
ubuntu:/$
```

which doesn't seen to involve any Haskell source files (with extension *.hs).

So my two questions are: 

Question (1): Is it true that the correct way incorporate this change on my system is to simply wait until the change has been pushed to Hackage, and then re-run the cabal as follows?

```
cabal install elm-yesod
```

This would imply that the correct workflow is:
- Fix and publish on GitHub.
- Push to Hackage.
- Use cabal to pull from Hackage
  ... with no "tweaking" in any files locally on my ubuntu server.

This makes sense, because it ensures that all changes are shared among everybody.

Question (2): Will there be an update here on GitHub notifying that this change has been pushed to Hackage, or should I look on Hackage itself to find out when the change has been pushed?

Thanks!

**Comment by ngunn** [comment]
On 02/03/13 03:54, DonaldScott wrote:

> Thanks!
> 
> Was this fix to #2 https://github.com/tazjin/elm-yesod/issues/2 and #3 https://github.com/tazjin/elm-yesod/issues/3 also related to the following Issue raised earlier today on the Elm GitHub page?
> 
> On Ubuntu 12.04 (32-bit) on AWS EC2 (after fresh install of haskell-platform and yesod-platform): "cabal install elm-yesod" gives error at Language/Elm/Yesod.hs:(65,1)-(73,46)
> evancz/Elm#109 https://github.com/evancz/Elm/issues/109
> 
> I presume it was (since that Issue on Elm's GitHub page, raised by me, involved ToJavaScript and Yesod-1.1.7.1).
> 
> It's late here now but I will try out this fix over the weekend. It seems like it was the only thing standing in the way of getting elm-yesod running in my particular installation (using AWS EC2, a medium-sized instance).
> 
> Thanks and it's good to see there is some activity here!
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/tazjin/elm-yesod/pull/4#issuecomment-14322354.
> 
> Sorry for delay -- UK timezone.

Yes, it's the same problem/fix (hadn't seen it on the Elm repo).
Had a very fast response from tazjin, so I wouldn't be surprised if (after he tests), it gets into hackage this weekend.
However (as a note of caution), I've had a little trouble with the examples in https://github.com/evancz/Elm/tree/master/Examples/elm-yesod (possibly to do with whether scripts end up in the <head> or <body>) and am looking into that.

```
 Neil.
```

**Comment by ngunn** [comment]
On 02/03/13 04:37, DonaldScott wrote:

> PS - Sorry to ask a very basic question, but I'm just getting started using GitHub, Cabal, Hackage etc.
> 
> No problem.  Detailed comment at end.
> 
> Here goes:
> 
> I see that the fix above has involving making the following tiny change in the file Elm/Language/Yesod.hs in the package elm-yesod:
> 
> https://github.com/ngunn/elm-yesod/commit/1a02abcb327dbe8cbdcef1ce6d1585bccbf741ac#Language/Elm/Yesod.hs
> 
> I also see above that this change has not yet been "pushed" to Hackage, although it will be soon.
> 
> So, since (as I understand) cabal "pulls" packages from Hackage, it seems that if I were to simply repeat the command now:
> 
> |cabal install elm-yesod
> |
> 
> this would probably not pull in the file incorporating this change.
> 
> True.
> 
> As an alternative, I tried searching (on my Ubuntu) using
> 
> |sudo find / -name Yesod.hs
> |
> 
> to find a file Yesod.hs, but I don't see one anywhere, so I guess cabal doesn't save local copies of source files, so it would not even make sense to attempt to update a local copy of Elm/Language/Yesod.hs - since there is none.
> 
> Yesod.hs is wrapped up in a tar.gz and is unpacked/compiled/cleaned by the installer.
> We can, however, find and unpack the tar.gz and make the change.
> 
> So my question is:
> 
> The proper way (the only way?) to incorporate this change on my system is to wait until the change has been pushed to Hackage, and then re-run:
> 
> |cabal install elm-yesod
> |
> 
> ?
> 
> Thanks!
> 
> Well, I'm not sure about a proper way, but this is what I did:

cd ~/.cabal/packages/hackage.haskell.org/elm-yesod/0.1.3/
tar xzf elm-yesod-0.1.3.tar.gz
vi elm-yesod-0.1.3/Language/Elm/Yesod.hs
(edit line 69 + save)
mv elm-yesod-0.1.3.tar.gz elm-yesod-0.1.3.tar.gz.old
tar czf elm-yesod-0.1.3.tar.gz elm-yesod-0.1.3
cabal install elm-yesod

Essentially, cabal downloads to .cabal/packages...somewhere
and installs from the tarballs.
We can unpack the tarball, make the change and repack and cabal is none the wiser.
(Note, there are cabal commands to do this unpacking/packing as well.)

A better way would be do download the repo from github and install from source directly, but I haven't tried that yet.

Hope that helps + I'd be interested to know how you get on,

```
 Neil.
```

**Comment by ngunn** [comment]
On 02/03/13 01:09, Vincent wrote:

> Thanks for this - I've been way too busy lately :/
> 
> Will also push to Hackage after testing tomorrow evening.
> 
> Thanks for noticing/updating so quickly -- much appreciated.

I have made a second pull request (small change to the same line of code for a different reason).
Found when I was trying to get the elm-yesod examples working.
I'm pleased that they now all work (with minor editing to the .elm files).

I don't believe that I can have broken anything based on the html output, but don't know enough about elm and yesod to be sure that it isn't more complex that I think.

```
 Neil.
```

**Pull request merged**
